### ISSUE TITLE
python 3.10 removes parser

### ISSUE THREAD

**Issue by krsna1729** [NetSys/bess#1035]
```
Traceback (most recent call last):
  File "/opt/bess/bessctl/./bessctl", line 42, in <module>
    import commands
  File "/opt/bess/bessctl/commands.py", line 52, in <module>
    import sugar
  File "/opt/bess/bessctl/sugar.py", line 34, in <module>
    import parser
ModuleNotFoundError: No module named 'parser'
```

https://docs.python.org/3/library/parser.html

```
Removed the parser module, which was deprecated in 3.9 due to the switch to the new PEG parser, as well as all the C source and header files that were only being used by the old parser, including node.h, parser.h, graminit.h and grammar.h.
```

https://docs.python.org/3.10/whatsnew/3.10.html#removed

**Comment by krsna1729** [comment]
[#347 (comment)](https://github.com/omec-project/upf-epc/pull/347#issuecomment-938286694)
