### ISSUE TITLE
AddActiveWorker() fails with pipeline loops

### ISSUE THREAD

**Issue by changlan** [NetSys/bess#421]
`AddActiveWorker()` loops forever for some pipeline. One example is `samples/nat.bess`:
```
Source() -> Rewrite(templates=packets) -> 0:nat:0 -> mac -> ip -> 1:nat:1 -> Sink()
```

`bessctl` command:
```
localhost:10514 $ run samples/nat
```

Output from `bessd` (with ASAN enabled):
```
...
W0427 19:48:35.617143  5857 module.h:466] Adding active worker for wid 0 to source0
ASAN:DEADLYSIGNAL
=================================================================
==5855==ERROR: AddressSanitizer: stack-overflow on address 0x7f77eee69fe8 (pc 0x000000889b1d bp 0x7f77eee6a040 sp 0x7f77eee69fd0 T2)
    #0 0x889b1c in std::_Hashtable<int, int, std::allocator<int>, std::__detail::_Identity, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::_M_find_before_node(unsigned long, int const&, unsigned long) const /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/bits/hashtable.h:1412
    #1 0x889303 in std::_Hashtable<int, int, std::allocator<int>, std::__detail::_Identity, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::_M_find_node(unsigned long, int const&, unsigned long) const /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/bits/hashtable.h:634:28
    #2 0x888e15 in std::pair<std::__detail::_Node_iterator<int, true, false>, bool> std::_Hashtable<int, int, std::allocator<int>, std::__detail::_Identity, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::_M_insert<int const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<int, false> > > >(int const&, std::__detail::_AllocNode<std::allocator<std::__detail::_Hash_node<int, false> > > const&, std::integral_constant<bool, true>) /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/bits/hashtable.h:1686:21
    #3 0x888bd1 in std::__detail::_Insert_base<int, int, std::allocator<int>, std::__detail::_Identity, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::insert(int const&) /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/bits/hashtable_policy.h:713:9
    #4 0x852485 in Module::AddActiveWorker(int) /bess/core/module.cc:267:3
    #5 0x8527a4 in Module::AddActiveWorker(int) /bess/core/module.cc:272:9
...
    #251 0x8527a4 in Module::AddActiveWorker(int) /bess/core/module.cc:272:9

SUMMARY: AddressSanitizer: stack-overflow /usr/bin/../lib/gcc/x86_64-linux-gnu/6.2.0/../../../../include/c++/6.2.0/bits/hashtable.h:1412 in std::_Hashtable<int, int, std::allocator<int>, std::__detail::_Identity, std::equal_to<int>, std::hash<int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, true, true> >::_M_find_before_node(unsigned long, int const&, unsigned long) const
Thread T2 created by T0 here:
    #0 0x7755d9 in pthread_create (/bess/core/bessd+0x7755d9)
    #1 0x14eb162 in std::thread::_M_start_thread(std::shared_ptr<std::thread::_Impl_base>, void (*)()) (/bess/core/bessd+0x14eb162)

==5855==ABORTING
```

**Comment by apanda** [comment]
Fixed by #424
