### ISSUE TITLE
Connection to localhost:10514 failed

### ISSUE THREAD

**Issue by czen199883** [NetSys/bess#503]
Hi,

First time bess user here. I tried setting up bess in a freshly installed Ubuntu 16.04 machine that has linux-4.4.0-78-generic kernel. After installing all the required libraries from ansible, I tried launching bessctl. Every time I run ``daemon start``, I get the following error:

```
<disconnected> $ daemon start 
Error: Connection to localhost:10514 failed
<disconnected> $
```

I am not sure where exactly I am making a mistake. A little assistance will be greatly appreciated :).

**Comment by changlan** [comment]
Hi! Could you try running BESS in foreground with verbose logging by

```
$ sudo ./bessd -f -k -v=1
```
The error message it outputs could help us find out where the problem is.

**Comment by czen199883** [comment]
Thanks for the quick response. This is the output I get. I do not see any error:

```
czen@mno:~/bess/bin$ sudo ./bessd -f -k -v=1
I0606 02:06:00.045258 82868 bessd.cc:178] flock
I0606 02:06:00.045486 82868 bessd.cc:218] There is another BESS daemon running (PID=82845)
I0606 02:06:00.045536 82868 bessd.cc:222] Sending SIGTERM signal...
I0606 02:06:00.145859 82868 bessd.cc:240] Old instance has been successfully terminated.
I0606 02:06:00.145965 82868 main.cc:32] Launching BESS daemon in process mode...
I0606 02:06:00.145997 82868 main.cc:38] bessd v0.2.0-635-ge9a9b8b
I0606 02:06:00.146546 82868 bessd.cc:416] Loading module: /home/czen/bess/core/modules/worker_split.so
I0606 02:06:00.150655 82868 bessd.cc:416] Loading module: /home/czen/bess/core/modules/vlan_split.so
... <More modules loaded here>
I0606 02:06:00.310730 82868 bessd.cc:416] Loading module: /home/czen/bess/core/modules/mttest.so
EAL: Detected 68 lcore(s)
EAL: No free hugepages reported in hugepages-1048576kB
I0606 02:06:00.422096 82868 dpdk.cc:58] EAL: Probing VFIO support...
I0606 02:06:01.462476 82868 dpdk.cc:58] EAL: PCI device 0000:05:00.0 on NUMA socket 0
I0606 02:06:01.462570 82868 dpdk.cc:58] EAL:   probe driver: 8086:1533 net_e1000_igb
I0606 02:06:01.462600 82868 dpdk.cc:58] EAL: PCI device 0000:06:00.0 on NUMA socket 0
I0606 02:06:01.462625 82868 dpdk.cc:58] EAL:   probe driver: 8086:1533 net_e1000_igb
I0606 02:06:01.615345 82868 packet.cc:71] Allocating 262143 buffers on socket 0: OK
I0606 02:06:01.615509 82868 pmd.cc:46] 0 DPDK PMD ports have been recognized:
I0606 02:06:01.615617 82868 bessctl.cc:1602] Server listening on 127.0.0.1:10514
I0606 02:06:01.615711157   82868 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 1, CQ timeout (msec): 1000
```

**Comment by sangjinhan** [comment]
Interesting. After running `bessctl daemon start` and seeing its failure, can you check `/tmp/bessd.INFO`? Log messages are supposed to be stored there, while `bessd -f` shows them directly on the screen.

**Comment by czen199883** [comment]
I did a little bit of debugging and found that the issue is arising in ``pybess/bess.py`` file in lines 97-104. The grpc channel is never really established.

This is the output of bessd.INFO:
```
Log file created at: 2017/06/06 03:45:55
Running on machine: mno
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0606 03:45:55.239416 83108 main.cc:38] bessd v0.2.0-635-ge9a9b8b
I0606 03:45:55.241166 83108 bessd.cc:416] Loading module: /home/czen/bess/core/modules/worker_split.so
I0606 03:45:55.245666 83108 bessd.cc:416] Loading module: /home/czen/bess/core/modules/vlan_split.so
I0606 03:45:55.249816 83108 bessd.cc:416] Loading module: /home/czen/bess/core/modules/queue_inc.so
I0606 03:45:55.253744 83108 bessd.cc:416] Loading module: /home/czen/bess/core/modules/update.so
I0606 03:45:55.257606 83108 bessd.cc:416] Loading module: /home/czen/bess/core/modules/port_out.so
I0606 03:45:55.261495 83108 bessd.cc:416] Loading module: /home/czen/bess/core/modules/timestamp.so
I0606 03:45:55.265350 83108 bessd.cc:416] Loading module: /home/czen/bess/core/modules/nat.so
I0606 03:45:55.269315 83108 bessd.cc:416] Loading module: /home/czen/bess/core/modules/bpf.so
I0606 03:45:55.273247 83108 bessd.cc:416] Loading module: /home/czen/bess/core/modules/random_drop.so
... <More modules loaded here>
W0606 03:45:55.421316 83108 bessd.cc:274] EAL: Detected 68 lcore(s)
W0606 03:45:55.422375 83108 bessd.cc:274] EAL: No free hugepages reported in hugepages-1048576kB
I0606 03:45:55.533803 83108 dpdk.cc:58] EAL: Probing VFIO support...
I0606 03:45:56.576664 83108 dpdk.cc:58] EAL: PCI device 0000:05:00.0 on NUMA socket 0
I0606 03:45:56.577056 83108 dpdk.cc:58] EAL:   probe driver: 8086:1533 net_e1000_igb
I0606 03:45:56.577133 83108 dpdk.cc:58] EAL: PCI device 0000:06:00.0 on NUMA socket 0
I0606 03:45:56.577200 83108 dpdk.cc:58] EAL:   probe driver: 8086:1533 net_e1000_igb
I0606 03:45:56.726320 83108 packet.cc:71] Allocating 262143 buffers on socket 0: OK
I0606 03:45:56.726506 83108 pmd.cc:46] 0 DPDK PMD ports have been recognized:
I0606 03:45:56.726635 83108 bessctl.cc:1602] Server listening on 127.0.0.1:10514
W0606 03:45:56.726856 83108 bessd.cc:274] I0606 03:45:56.726821429   83108 server_builder.cc:247]      Synchronous server. Num CQs: 1, Min pollers: 1, Max Pollers: 1, CQ timeout (msec): 1000

```

**Comment by changlan** [comment]
Ah. Is that because `localhost` isn't in your `/etc/hosts` so that it didn't get resolved to `127.0.0.1`?

**Comment by czen199883** [comment]
Hmm. I don't think so. These are the contents of ``/etc/hosts``:

```
127.0.0.1       localhost
127.0.1.1       mno

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
```

**Comment by czen199883** [comment]
My machine is behind a firewall and I generally have to use proxies to access services over the Internet. Does ``bess`` connect to any external service during initialization?

**Comment by sangjinhan** [comment]
Perhaps this manual test might help:
```
$ python
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
>>> import service_pb2_grpc
>>> channel = grpc.insecure_channel('localhost:10514')
>>> stub = service_pb2_grpc.BESSControlStub(channel)
>>> stub.GetVersion(service_pb2_grpc.bess__msg__pb2.EmptyArg())
version: "v0.2.0-639-g9ce75b5-dirty"
```

If it fails, please try 127.0.0.1 in place of localhost

**Comment by czen199883** [comment]
I get the following error when I try to import ``service_pb2_grpc``:
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
>>> import service_pb2_grpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named service_pb2_grpc
>>> import service_pb2_grpc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named service_pb2_grpc
```

**Comment by sangjinhan** [comment]
Did you do it in `bess/pybess` directory? If so, there is no `service_pb2_grpc.py` file? `build.py` in the root directory should have created it...

**Comment by czen199883** [comment]
Sorry. I did not read the (in ``bess/pybess`` directory) part of the message by mistake.
This is the output that I get:
```
Python 2.7.12 (default, Nov 19 2016, 06:48:10)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import grpc
>>> import service_pb2_grpc
>>> channel = grpc.insecure_channel('127.0.0.1:10514')
>>> stub = service_pb2_grpc.BESSControlStub(channel)
>>> stub.GetVersion(service_pb2_grpc.bess__msg__pb2.EmptyArg())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 507, in __call__
    return _end_unary_response_blocking(state, call, False, deadline)
  File "/usr/local/lib/python2.7/dist-packages/grpc/_channel.py", line 455, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with (StatusCode.UNAVAILABLE, Endpoint read failed)>
>>>
```

**Comment by sangjinhan** [comment]
It seems like a firewall issue indeed. To make sure, can you connect to localhost:10514 without grpc?
```
$ telnet localhost 10514
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
�@hello   <- I typed hello<CR>
Connection closed by foreign host.
```

**Comment by czen199883** [comment]
Yes. It does connect via telnet. Thanks for debugging the issue. Is there any way bess could run under these conditions? Or should I find a machine that has direct access to the Internet?

**Comment by sangjinhan** [comment]
No.... there should be no Internet access needed at all. Perhaps the installed gRPC Python package is doing something funky.... How about giving it a try to reinstall `grpcio` with `pip`?

**Comment by nrdmao** [comment]
Is python-futures installed on your machine? You will see this error if it
is not installed. Or at least I have seen this error if it was not
installed.

Note that a better fix in bess may be to modify libbess-python/bess.py;
change the "import service_pb2"  to “import service_pb2_grpc”;

and change "service_pb2.BESSControlStub(self.channel)" to "service_pb2_grpc.
BESSControlStub(self.channel)".

Thanks,

Jim

**Comment by czen199883** [comment]
I tried reinstalling grpcio using ``pip install grpcio``. I also tried installing ``python-futures`` package. Both ideas failed to work.

**Comment by bave** [comment]
I also met the same situation.

In that situation, it is probably impossible to connect using by grpc,
 if proxy settings are written in environment variables. So, I suggest
adding **export no_proxy='127.0.0.1'** to your environment variable.

By doing so, I was able to do it well.

**Comment by btlcmr0702** [comment]
I also met this problem.
And I follow the advice of bave (above) and solved! Really thanks.
We can also find the problem by check where the packets were forwarder from python.
Because I use proxy so the packets can't forward to localhost.

**Comment by xnhp0320** [comment]
I have also met this problem, however I unset everything that is related to proxy.
It turns out that perhaps the BESSD launch is slow, so when the first time bessctl
tries to connect to the server, it gets self.status == ChannelConnectivity.TRANSIENT_FAILURE,
which terminates all the retries. 

I change the code to 

        while not self.is_connected():
            if self.status in [#grpc.ChannelConnectivity.TRANSIENT_FAILURE,
                               grpc.ChannelConnectivity.SHUTDOWN,
                               self.BROKEN_CHANNEL]:
                print(self.status)
                self.disconnect()
                raise self.APIError(
                    'Connection to {} failed'.format(grpc_url))
            time.sleep(0.1)

It works.

**Comment by btlcmr0702** [comment]
Thank you for your reply.

In our environment, we just unset the proxy then the traffic can go to localhost, or the traffic will go the address set by proxy.

But I will try this way to verify.


Best Regards


________________________________
发件人: Peng He <notifications@github.com>
发送时间: 2018年5月1日 0:35
收件人: NetSys/bess
抄送: uCantSeeMe; Comment
主题: Re: [NetSys/bess] Connection to localhost:10514 failed (#503)


I have also met this problem, however I unset everything that is related to proxy.
It turns out that perhaps the BESSD launch is slow, so when the first time bessctl
tries to connect to the server, it gets self.status == ChannelConnectivity.TRANSIENT_FAILURE,
which terminates all the retries.

I change the code to

    while not self.is_connected():
        if self.status in [#grpc.ChannelConnectivity.TRANSIENT_FAILURE,
                           grpc.ChannelConnectivity.SHUTDOWN,
                           self.BROKEN_CHANNEL]:
            print(self.status)
            self.disconnect()
            raise self.APIError(
                'Connection to {} failed'.format(grpc_url))
        time.sleep(0.1)


It works.

―
