### ISSUE TITLE
Error installing bess in a fresh Ubuntu 16.04 VM

### ISSUE THREAD

**Issue by h0ax-ki1l3r** [NetSys/bess#574]
Hi,

I was trying to install BESS in a fresh Ubuntu 16.04 LTS VM. I had given the VM enough RAM and CPU power. There was no error while installing. As soon as I was trying to run ./bessctl it gave me what looked like a Python package error.

```
h0ax@bess:~/bess/bessctl$ ./bessctl 
Cannot import the API module (pybess)
Traceback (most recent call last):
  File "./bessctl", line 20, in <module>
    from pybess.bess import *
  File "/home/h0ax/bess/bessctl/../pybess/bess.py", line 10, in <module>
    from . import service_pb2
ImportError: cannot import name service_pb2
h0ax@bess:~/bess/bessctl$ 
```

Can someone help me on this or let me know what am I missing here?

Thanks!

**Comment by h0ax-ki1l3r** [comment]
My bad, I had forgotten to build it, haha!
