### ISSUE TITLE
nat module test fails

### ISSUE THREAD

**Issue by nrdmao** [NetSys/bess#789]
Hi,

The following test fails:

$ TEST_NAME=nat bessctl/bessctl run $(pwd)/bessctl/conf/testing/run_module_tests
Environment variable "TEST_PATH" is not set. Using default value "/home/jmurphy/bess/bess-public/bessctl/module_tests"
[Warn] This test framework may be removed soon. Please consider porting your existing test code into new framework 'bessctl/run_module_tests.py'.
-- Running Module Tests for nat.py --
test_nat_icmp (__builtin__.BessNatTest) ... ok
test_nat_selfconfig (__builtin__.BessNatTest) ... arg  {'ext_addrs': [{'port_ranges': [{'begin': 1, 'end': 1024}, {'begin': 1025, 'end': 65535}], 'ext_addr': '192.168.1.1'}]}
iconf {'ext_addrs': [{'port_ranges': [{'begin': 1, 'end': 1024}, {'begin': 1025, 'end': 65535}], 'ext_addr': '192.168.1.1'}]}
cur_config {}
expected_config {}
ok
test_nat_tcp (__builtin__.BessNatTest) ... ok
test_nat_udp (__builtin__.BessNatTest) ... FAIL
test_nat_udp_with_cksum (__builtin__.BessNatTest) ... FAIL

======================================================================
FAIL: test_nat_udp (__builtin__.BessNatTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/jmurphy/bess/bess-public/bessctl/module_tests/nat.py", line 91, in test_nat_udp
    self._test_l4(nat, scapy.UDP(sport=56797, dport=53), '192.168.1.1')
  File "/home/jmurphy/bess/bess-public/bessctl/module_tests/nat.py", line 78, in _test_l4
    self.assertSamePackets(eth / ip_natted / l4_natted / l7, pkt_natted)
  File "/home/jmurphy/bess/bess-public/bessctl/test_utils.py", line 180, in assertSamePackets
    '"%s" != "%s"' % (pkt_str(pkt1), pkt_str(pkt2)))
AssertionError: "06163e1b7232021e679f4dae080045000026000100004011a90dc0a80101080808087fd4003500128de768656c6c6f776f726c64" != "06163e1b7232021e679f4dae080045000026000100004011a90dc0a80101080808087fd4003500128de768656c6c6f776f726c640000"
...

Are these tests still being maintained and are they used as part of continuous integration?

Thanks,

Jim

**Comment by chris3torek** [comment]
FWIW (since I'm about to poke at NAT) I just ran this test and it worked fine for me. I think I _have_ seen the "two all-zero bytes appended to or removed from a packet" error elsewhere, I forget where, though.
